# Generated by Django 6.1.1 on 2026-09-29 00:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['zip_code'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_enabled', models.BooleanField(default=True)),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('3.99'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('free_delivery_minimum', models.DecimalField(blank=True, decimal_places=2, default=Decimal('30.00'), help_text='Subtotal at which delivery becomes free. Leave blank to never waive the fee.', max_digits=8, null=True)),
                ('delivery_minimum_subtotal', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0725'), help_text='Sales tax as a decimal, e.g. 0.0725 for 7.25%.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('pickup_prep_minutes', models.PositiveSmallIntegerField(default=15)),
                ('delivery_extra_minutes', models.PositiveSmallIntegerField(default=25, help_text='Added on top of prep time for delivery orders.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fulfillment settings',
                'verbose_name_plural': 'fulfillment settings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In progress'), ('ready_for_pickup', 'Ready for pickup'), ('completed', 'Picked up'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered')], default='received', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_phone', models.CharField(blank=True, max_length=10)),
                ('delivery_street', models.CharField(blank=True, max_length=255)),
                ('delivery_unit', models.CharField(blank=True, max_length=50)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_state', models.CharField(blank=True, max_length=2)),
                ('delivery_zip', models.CharField(blank=True, max_length=5)),
                ('delivery_instructions', models.CharField(blank=True, max_length=255)),
                ('estimated_ready_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
